// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  section_heading: dynamic(() => import("./SectionHeading")),
  test: dynamic(() => import("./Test")),
};
